name: Build Snowstorm Project CD
on:
  push:
    branches:
      - main

jobs:
  deploy_project:
    name: Test Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project Repositories
      uses: actions/checkout@v3

    - name: Configure Environment - V16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: "Automated Version Bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Bump version and push tag
     # id: tag_version
      #uses: mathieudutour/github-tag-action@v6.0
      #with:
      #  github_token: ${{ secrets.GITHUB_TOKEN }}
       # custom_tag: 2.1.1
        #tag_prefix: V
        # default_bump: minor
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
