name: Build Snowstorm Project CD
on:
  push:
    branches:
      - main

jobs:
  deploy_project:
    name: Test Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project Repositories
      uses: actions/checkout@v3

    - name: Configure Environment - V16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Obtain NPM Version
      id: version
      uses: martinbeentjes/npm-get-version-action@main
        
    - name: Build Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ '3.1.1' }}
