name: Build Snowstorm Project CD
on:
  push:
    branches:
      - main

jobs:
  deploy_project:
    name: Test Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project Repositories
      uses: actions/checkout@v3

    - name: Configure Environment - V16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: get-npm-version
      id: version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.version.outputs.current-version}}
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
